### ISSUE TITLE
[WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1

### ISSUE THREAD

**Issue by jomiva** [lewisxhe/CryptocurrencyLib#2]
My code:
#include <Arduino.h>
#include "CoinMarketCapApi.h"
#include <WiFi.h>
#include "WiFiClientSecure.h"

#define ssid "ssid"
#define password "password"
#define apiKey "apikey"

WiFiClientSecure client;
CoinMarketCapApi api(client, apiKey);

void printTickerData(String ticker)
{
  CMCTickerResponse response = api.GetTickerInfo(ticker, "USD");
  if (response.error == "")
  {
    Serial.print("ID: ");
    Serial.println(response.id);
    Serial.print("Name: ");
    Serial.println(response.name);
    Serial.print("Symbol: ");
    Serial.println(response.symbol);

    Serial.print("Rank: ");
    Serial.println(response.cmc_rank);

    Serial.print("Price: ");
    Serial.println(response.price);

    Serial.print("24h Volume: ");
    Serial.println(response.volume_24h);
    Serial.print("Market Cap: ");
    Serial.println(response.market_cap);

    Serial.print("Circulating Supply: ");
    Serial.println(response.circulating_supply);
    Serial.print("Total Supply: ");
    Serial.println(response.total_supply);

    Serial.print("Percent Change 1h: ");
    Serial.println(response.percent_change_1h);
    Serial.print("Percent Change 24h: ");
    Serial.println(response.percent_change_24h);
    Serial.print("Percent Change 7d: ");
    Serial.println(response.percent_change_7d);
    Serial.print("Last Updated: ");
    Serial.println(response.last_updated);
  }
}

void setup()
{
  Serial.begin(115200);
  Serial.println(F("Boot Ticker"));

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED)
  {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void loop()
{
  printTickerData("BTC");
  delay(20000);
}

Expectated result:
get btc info

result:
/v1/cryptocurrency/quotes/latest?symbol=BTC&convert=USD
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
deserializeJson() failed: EmptyInput

Does anyone know how to solve it?

**Comment by ntalmate** [comment]
i hope you did not forget to insert your actual ssid , password and api key here 

#define ssid "ssid"
#define password "password"
#define apiKey "apikey" 

btw this:

"/v1/cryptocurrency/quotes/latest?symbol=BTC&convert=USD
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
deserializeJson() failed: EmptyInput"

means that before "deserializeJson(doc,response)" if i remember correctly ,  the api call failed or returned nothing, hence the response is empty, and the deserializeJson() function would be pointless at this point, so it throws an exception.

i get the same error, but in my case the problem might be my api key being invalid, not the missing parameters.

try filling in your ssid, etc, then let me now if it worked

**Comment by Juhani-H** [comment]
im getting this EmptyInput too.. nothing changed (ssid/password ofcourse) and this is output: 

Getting ticker data for BTC
15:23:05.164 -> /v1/cryptocurrency/quotes/latest?symbol=BTC&convert=EUR
15:23:05.164 -> deserializeJson() failed: EmptyInput
15:23:05.164 -> Error getting data: EmptyInput
15:23:05.164 -> ---------------------------------
 --- whats wrong with this.. ?

**Comment by jomiva** [comment]
I "fix it" using client's method .insecure() inside CoinMarketApi. This is not a solution because now I get warnings about insecure requests.. but at least I can get the info from server and work with it.
